#!/bin/bash
gcc -std=c99 enc_server.c -o enc_server
gcc -std=c99 dec_server.c -o dec_server
gcc -std=c99 enc_client.c -o enc_client
gcc -std=c99 dec_client.c -o dec_client
gcc -std=c99 keygen.c -o keygen
